version:      "0027--11-Sep-2022"
copyright:    "2022"
author:       "Alfredooooooo"
name:         "Alfredo Austin"
title:        "OS222: Operating Systems 2022-2"
githublink:   "https://github.com/Alfredooooooo/os222"
myloglink:    "/TXT/mylog.txt"
tarballlink:  "https://os.vlsm.org/Log/Alfredooooooo.tar.bz2.txt"
encoding:     UTF-8
markdown:     kramdown
input:        GFM
hard_wrap:    false
github:       [metadata]
